/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AutoTOCPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/globalData/globalData.ts
var tableStart = "<!-- Table of Contents ";
var endComment = "-->";
var endTable = "<!-- End of TOC -->";

// src/markdownFunctions/removeCharactersFromString.ts
function removeCharactersFromString(str, removeStr) {
  let re = new RegExp(removeStr, "g");
  return str.replace(re, "");
}

// src/markdownFunctions/removeListOfCharactersFromString.ts
function removeListOfCharactersFromString(str, removeCharactersList) {
  removeCharactersList.forEach(
    (removeStr) => {
      str = removeCharactersFromString(str, removeStr);
    }
  );
  return str;
}

// src/markdownFunctions/stripMarkdown.ts
function stripMarkdown(text) {
  return text.replace(/\*\*/g, "").replace(/\*/g, "").replace(/`/g, "").replace(/==/g, "").replace(/~~/g, "").replace(/\[([^\]]+)\]\([^)]+\)/g, "$1");
}
function stripHtml(text) {
  return text.replace(/<[^>]+>/g, "");
}
function stripWikilinks(text) {
  return text.replace(/\[\[([^\]|]+)\|([^\]]+)\]\]/g, "$2").replace(/\[\[([^\]]+)\]\]/g, "$1").replace(/\[\[/g, "").replace(/\]\]/g, "");
}
function stripFootnotes(text) {
  return text.replace(/\[\^[^\]]+\]/g, "");
}
function stripFootnotesForHeading(text) {
  return text.replace(/\[\^(.+?)\]/g, "[ $1]");
}
function sanitizeLinkTarget(text) {
  let sanitized = text;
  sanitized = stripWikilinks(sanitized);
  sanitized = stripFootnotesForHeading(sanitized);
  return sanitized.trim();
}
function sanitizeHeadingText(text, textStyling) {
  let sanitized = text;
  if (textStyling.removeTextStyling) {
    sanitized = stripMarkdown(sanitized);
  }
  if (textStyling.removeHtml) {
    sanitized = stripHtml(sanitized);
  }
  if (textStyling.removeWikilinks) {
    sanitized = stripWikilinks(sanitized);
  }
  if (textStyling.removeFootnotes) {
    sanitized = stripFootnotes(sanitized);
  }
  return sanitized.trim();
}

// src/markdownFunctions/createSubheadingIndex.ts
function createSubheadingIndex(fileName, content, removeCharList, textStyling) {
  if (content == void 0) {
    return "";
  }
  let subheadingContent = "";
  let maxDepth = 0;
  let minDepth = content.indexOf(" ");
  let tempContent = [];
  content.split("\n").forEach((line) => {
    const spaceIndex = line.indexOf(" ");
    if (spaceIndex > maxDepth) {
      maxDepth = spaceIndex;
    }
    if (spaceIndex < minDepth) {
      minDepth = spaceIndex;
    }
    tempContent.push([spaceIndex, line.slice(spaceIndex).trim()]);
  });
  let indexNumArray = new Array(maxDepth).fill(0);
  tempContent.forEach((headingContent) => {
    const headingDepth = headingContent[0];
    const headingTitle = headingContent[1];
    const headingSignifier = "#".repeat(headingDepth);
    const tabIndent = "	".repeat(headingDepth - minDepth);
    const headingNum = indexNumArray[headingDepth - 1] + 1;
    indexNumArray[headingDepth - 1] += 1;
    for (let i = headingDepth; i < maxDepth; i++) {
      indexNumArray[i] = 0;
    }
    const linkTarget = sanitizeLinkTarget(headingTitle);
    const displayText = sanitizeHeadingText(removeListOfCharactersFromString(headingTitle, removeCharList), textStyling);
    subheadingContent += `${tabIndent}${headingNum}. [[${fileName}${headingSignifier}${linkTarget}|${displayText}]]
`;
  });
  return subheadingContent;
}

// src/markdownFunctions/lineIsHeading.ts
function lineIsHeading(str) {
  if (str[0] != "#") {
    return false;
  }
  const spaceIndex = str.indexOf(" ");
  if (spaceIndex == -1) {
    return false;
  }
  if (str.slice(0, spaceIndex) != "#".repeat(spaceIndex)) {
    return false;
  }
  return true;
}

// src/markdownFunctions/createSubheadingNonIndex.ts
function createSubheadingNonIndex(fileName, content, arrowType, removeCharList, textStyling) {
  if (content == void 0) {
    return "";
  }
  let subheadingContent = "";
  const space = " ";
  let minDepth = content.indexOf(space);
  let tempcontent = content.split("\n").filter((t) => {
    return lineIsHeading(t);
  });
  tempcontent.forEach((t) => {
    const spaceIndex = t.indexOf(space);
    if (spaceIndex < minDepth) {
      minDepth = spaceIndex;
    }
  });
  tempcontent.forEach((line) => {
    const spaceIndex = line.indexOf(space);
    const heading = line.slice(0, spaceIndex);
    const headingTitle = line.slice(spaceIndex).trim();
    const tabIndent = "	".repeat(spaceIndex - minDepth);
    const linkTarget = sanitizeLinkTarget(headingTitle);
    const displayText = sanitizeHeadingText(removeListOfCharactersFromString(headingTitle, removeCharList), textStyling);
    subheadingContent += `${tabIndent}${arrowType} [[${fileName}${heading}${linkTarget}|${displayText}]]
`;
  });
  return subheadingContent;
}

// src/markdownFunctions/removeCodeBlocks.ts
function removeCodeBlocks(str) {
  const codeBlockIndicator = "```";
  const regString = `${codeBlockIndicator}((.|
|\r)*?)${codeBlockIndicator}`;
  let re = new RegExp(regString, "g");
  return str.replace(re, "");
}

// src/markdownFunctions/contentToToc.ts
function contentToTOC(fileName, content, plugin, arrowType, title, codeBlocks) {
  const numberArrow = "Index";
  const newLine = "\n";
  const heading = "# ";
  const propertySeparator = " | ";
  const hasCodeBlocks = "y";
  if (!arrowType) {
    arrowType = plugin.settings.tocSettings.arrowType;
  }
  if (!title) {
    title = plugin.settings.tocSettings.title;
  }
  if (!codeBlocks) {
    codeBlocks = plugin.settings.tocSettings.codeBlocks;
  }
  let table_of_contents = tableStart + "arrowType: " + arrowType + propertySeparator + "title: " + title + " " + propertySeparator + "codeBlocks: " + codeBlocks + " " + endComment + newLine + heading + title + newLine;
  if (codeBlocks === hasCodeBlocks) {
    content = removeCodeBlocks(content);
  }
  const tabCheck = content.indexOf("# ");
  if (tabCheck == -1) {
    return table_of_contents + endTable + "\n";
  }
  const headings = content.split(newLine).filter((t) => {
    return lineIsHeading(t);
  }).join("\n");
  if (arrowType == numberArrow) {
    table_of_contents += createSubheadingIndex(fileName, headings, plugin.settings.removeCharactersFromTitles, plugin.settings.textStyling) + "\n";
  } else {
    table_of_contents += createSubheadingNonIndex(fileName, headings, arrowType, plugin.settings.removeCharactersFromTitles, plugin.settings.textStyling) + "\n";
  }
  table_of_contents += endTable + "\n";
  return table_of_contents;
}

// src/markdownFunctions/splitMarkdownUp.ts
function splitMarkdownUp(file) {
  const frontMatterCheckLine = "---";
  const tocStart = file.indexOf(tableStart);
  if (file.slice(0, 3) != frontMatterCheckLine) {
    if (tocStart == -1) {
      return ["", "", "", file];
    }
    const tocEnd2 = file.indexOf(endTable) + endTable.length;
    return [
      "",
      file.slice(0, tocStart),
      file.slice(tocStart, tocEnd2),
      file.slice(tocEnd2)
    ];
  }
  const frontMatterEndString = "\n---\n";
  const endFrontMatter = file.indexOf(frontMatterEndString);
  if (endFrontMatter == -1) {
    if (tocStart == -1) {
      return ["", "", "", file];
    }
    const tocEnd2 = file.indexOf(endTable) + endTable.length;
    return [
      "",
      file.slice(0, tocStart),
      file.slice(tocStart, tocEnd2),
      file.slice(tocEnd2)
    ];
  }
  if (tocStart == -1) {
    const splitIndex2 = endFrontMatter + frontMatterEndString.length;
    return [file.slice(0, splitIndex2), "", "", file.slice(splitIndex2)];
  }
  const tocEnd = file.indexOf(endTable) + endTable.length;
  const splitIndex = endFrontMatter + frontMatterEndString.length;
  return [
    file.slice(0, splitIndex),
    file.slice(splitIndex, tocStart),
    file.slice(tocStart, tocEnd),
    file.slice(tocEnd)
  ];
}

// src/markdownFunctions/createToc.ts
function createToc(fileContent, fileName, plugin, arrowTypeTOC, title) {
  const fileSplit = splitMarkdownUp(fileContent);
  const frontmatter = fileSplit[0];
  const preTOC = fileSplit[1];
  if (!arrowTypeTOC) {
    arrowTypeTOC = plugin.settings.tocSettings.arrowType;
  }
  if (!title) {
    title = plugin.settings.tocSettings.title;
  }
  const postTOC = fileSplit[3];
  const content = preTOC + postTOC;
  const toc = contentToTOC(fileName, content, plugin, arrowTypeTOC);
  const result = frontmatter + preTOC + toc + "\n" + postTOC.trim();
  return result;
}

// src/markdownFunctions/checkTOC.ts
async function checkToc(file) {
  const fileContent = await this.app.vault.read(file);
  const tocStart = fileContent.indexOf(tableStart);
  if (tocStart == -1) {
    return false;
  }
  const tocEnd = fileContent.indexOf(endTable);
  if (tocEnd > tocStart) {
    return true;
  }
  return false;
}

// src/markdownFunctions/oldToc.ts
function oldToc(fileContent) {
  const fileSplit = splitMarkdownUp(fileContent);
  return fileSplit[2];
}

// ArrowType/choices/arrowTypeChoices.ts
var arrowTypeChoices = ["Index", ">", "-"];

// src/markdownFunctions/tocProperties.ts
var import_obsidian = require("obsidian");

// src/tocSettings.ts
var DEFAULT_INLINE_TOCSETTINGS = {
  arrowType: arrowTypeChoices[0],
  title: "Table of contents",
  codeBlocks: "n"
};

// src/markdownFunctions/tocProperties.ts
function tocProperties(tocHeading, plugin) {
  const propertySeparator = " | ";
  const endCommentIndex = tocHeading.indexOf(endComment);
  if (endCommentIndex == -1) {
    new import_obsidian.Notice("The end comment the start of the table of contents was missing. Using default settings.");
    return plugin.settings.tocSettings;
  }
  let styleText = tocHeading.slice(tableStart.length, endCommentIndex).trim();
  const tocProperties2 = styleText.split(propertySeparator).flatMap((text) => {
    const valueSeparator = text.indexOf(":") + 1;
    const value = text.slice(valueSeparator).trim();
    return value;
  });
  if (tocProperties2.length < Object.keys(DEFAULT_INLINE_TOCSETTINGS).length) {
    new import_obsidian.Notice("Your toc was missing a property. Using default properties");
    return plugin.settings.tocSettings;
  }
  const title = tocProperties2[1];
  const codeBlocks = tocProperties2[2];
  if (arrowTypeChoices.indexOf(tocProperties2[0]) > -1) {
    const arrowType2 = tocProperties2[0];
    const tocSettings2 = { arrowType: arrowType2, title, codeBlocks };
    return tocSettings2;
  }
  new import_obsidian.Notice("The arrow type you entered was not recognised. Using default setting arrow.");
  const arrowType = plugin.settings.tocSettings.arrowType;
  const tocSettings = { arrowType, title, codeBlocks };
  return tocSettings;
}

// src/markdownFunctions/shouldUpdateToc.ts
async function shouldUpdateToc(file, plugin) {
  const fileName = file.basename;
  const fileSplit = splitMarkdownUp(await this.app.vault.read(file));
  const content = fileSplit[1] + fileSplit[3];
  const tocProp = tocProperties(fileSplit[2], plugin);
  const toc = contentToTOC(fileName, content, plugin, tocProp.arrowType, tocProp.title, tocProp.codeBlocks).trim();
  const oldTocMD = oldToc(await this.app.vault.cachedRead(file)).trim();
  const updateToc = !(toc === oldTocMD);
  return [updateToc, toc];
}

// src/markdownFunctions/updateFileToc.ts
function updateFileToc(fileContent, toc) {
  const tableStartIndex = fileContent.indexOf(tableStart);
  const tableEndIndex = fileContent.indexOf(endTable) + endTable.length;
  return fileContent.slice(0, tableStartIndex) + toc + fileContent.slice(tableEndIndex);
}

// src/textRemovingPermissions.ts
var defaultTextAdjustProperties = {
  removeWikilinks: true,
  removeFootnotes: true,
  removeHtml: false,
  removeTextStyling: true
};

// src/totalTocSettings.ts
var DEFAULT_SETTINGS = {
  tocSettings: DEFAULT_INLINE_TOCSETTINGS,
  removeCharactersFromTitles: [],
  hiddenLineIndicator: -1,
  textStyling: defaultTextAdjustProperties
};

// src/modal/RemoveCharactersModal.ts
var import_obsidian4 = require("obsidian");

// src/modal/fillOutModal.ts
var import_obsidian3 = require("obsidian");

// src/functions/canAddToList.ts
var import_obsidian2 = require("obsidian");
function canAddToList(str, list) {
  let allowed = true;
  list.forEach((word) => {
    if (word === str.trim()) {
      new import_obsidian2.Notice("This word is already excluded.");
      allowed = false;
      return false;
    }
  });
  return allowed;
}

// src/Data/escapedCharacters.ts
var escapedCharacters = ["*", "+", "?", ".", "^", "$", "-", "(", ")", "[", "]", "{", "}", "\\", "|"];

// src/modal/reformatStringForRegex.ts
function reformatStringForRegex(str) {
  const escape = "\\";
  let reformatStr = "";
  for (let i = 0; i < str.length; i++) {
    let escapeChar = false;
    for (let j = 0; j < escapedCharacters.length; j++) {
      if (str[i] == escapedCharacters[j]) {
        reformatStr += escape + str[i];
        escapeChar = true;
        break;
      }
    }
    if (!escapeChar) {
      reformatStr += str[i];
    }
  }
  return reformatStr;
}

// src/modal/fillOutModal.ts
function fillOutModal(contentEl, plugin) {
  contentEl.empty();
  new import_obsidian3.Setting(contentEl).setName("List of words excluded from title.").setHeading();
  plugin.settings.removeCharactersFromTitles.forEach((string) => {
    new import_obsidian3.Setting(contentEl).setName(string).addButton((btn) => {
      btn.setButtonText("Remove this from list");
      btn.onClick(async () => {
        plugin.settings.removeCharactersFromTitles = plugin.settings.removeCharactersFromTitles.filter((t) => {
          return t != string;
        });
        await plugin.saveSettings();
        fillOutModal(contentEl, plugin);
      });
    });
  });
  let excludedCharacter = "";
  new import_obsidian3.Setting(contentEl).setName("Add New excluded characters").addTextArea((cb) => {
    cb.setValue(excludedCharacter);
    cb.onChange((value) => {
      excludedCharacter = value;
    });
  }).addButton((btn) => {
    btn.setButtonText("Add to list");
    btn.onClick(async () => {
      const reformattedStr = reformatStringForRegex(excludedCharacter);
      if (canAddToList(reformattedStr, plugin.settings.removeCharactersFromTitles)) {
        plugin.settings.removeCharactersFromTitles.push(reformattedStr);
        await plugin.saveSettings();
        fillOutModal(contentEl, plugin);
      }
    });
  });
}

// src/modal/RemoveCharactersModal.ts
var RemoveCharactersFromTitles = class extends import_obsidian4.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    fillOutModal(contentEl, this.plugin);
  }
};

// src/markdownFunctions/headingUpdated.ts
function headingUpdated(str) {
  const headingStart = "#";
  if (str[0] != headingStart) {
    return false;
  }
  const space = " ";
  const spaceIndex = str.indexOf(space);
  if (spaceIndex == -1) {
    return false;
  }
  if (str.slice(0, spaceIndex) != headingStart.repeat(spaceIndex)) {
    return false;
  }
  return true;
}

// src/main.ts
var TOCTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
  }
  display() {
    const { containerEl } = this;
    ;
    containerEl.empty();
    new import_obsidian5.Setting(containerEl).setName("Adjust table of contents conditions").setHeading();
    new import_obsidian5.Setting(containerEl).setName("Choose list style").setDesc("Choose the arrow type for your table of contents").addDropdown((dropdown) => {
      for (let i = 0; i < arrowTypeChoices.length; i++) {
        dropdown.addOption(arrowTypeChoices[i], arrowTypeChoices[i]);
      }
      dropdown.setValue(this.plugin.settings.tocSettings.arrowType);
      dropdown.onChange(async (value) => {
        this.plugin.settings.tocSettings.arrowType = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian5.Setting(containerEl).setName("Choose the title for the table of contents").setDesc("How do you want the table of contents to start.").addTextArea((cb) => {
      cb.setValue(this.plugin.settings.tocSettings.title);
      cb.onChange(async (value) => {
        this.plugin.settings.tocSettings.title = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian5.Setting(containerEl).setName("Does your page contain code blocks").setDesc("The plugin needs to know to avoid the comments in these code blocks.").addDropdown((db) => {
      db.addOption("y", "y");
      db.addOption("n", "n");
      db.setValue(this.plugin.settings.tocSettings.codeBlocks);
      db.onChange(async (value) => {
        this.plugin.settings.tocSettings.codeBlocks = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian5.Setting(containerEl).setName("Adjust title display in table of contents").setHeading();
    new import_obsidian5.Setting(containerEl).setName("Remove text styling from titles in TOC.").setDesc("Will remove bold fonts and strikethroughs in table of contents.").addToggle((cb) => {
      cb.setValue(this.plugin.settings.textStyling.removeTextStyling);
      cb.onChange(async (value) => {
        this.plugin.settings.textStyling.removeTextStyling = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian5.Setting(containerEl).setName("Remove html from titles in TOC.").setDesc("Removes and html elements you have in titles.").addToggle((cb) => {
      cb.setValue(this.plugin.settings.textStyling.removeHtml);
      cb.onChange(async (value) => {
        this.plugin.settings.textStyling.removeHtml = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian5.Setting(containerEl).setName("Remove wikilinks from titles in TOC.").setDesc("If you have links in titles, will remove the [[ and ]] in the table of contents.").addToggle((cb) => {
      cb.setValue(this.plugin.settings.textStyling.removeWikilinks);
      cb.onChange(async (value) => {
        this.plugin.settings.textStyling.removeWikilinks = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian5.Setting(containerEl).setName("Remove footnotes from titles in TOC.").setDesc("Removes footnotes from title in table of contents.").addToggle((cb) => {
      cb.setValue(this.plugin.settings.textStyling.removeFootnotes);
      cb.onChange(async (value) => {
        this.plugin.settings.textStyling.removeFootnotes = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian5.Setting(containerEl).setName("Add New characters to remove from titles.").setDesc("Individualise what you want in your TOC by removing what you don't want.").addButton((btn) => {
      btn.setButtonText("Open modal to organise this.");
      btn.onClick(() => {
        new RemoveCharactersFromTitles(this.app, this.plugin).open();
      });
    });
  }
};
var AutoTOCPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new TOCTab(this.app, this));
    this.addCommand({
      id: "create-table-of-contents",
      name: "Create table of contents",
      callback: async () => {
        const file = this.app.workspace.getActiveFile();
        if (file) {
          const fileName = file.basename;
          this.app.vault.process(file, (fileContent) => {
            return createToc(fileContent, fileName, this);
          });
        }
      }
    });
    this.addCommand({
      id: "create-table-of-contents-at-cursor",
      name: "Create table of contents at cursor",
      editorCallback: (editor, ctx) => {
        var _a;
        const rawFileName = (_a = ctx.file) == null ? void 0 : _a.name;
        const periodIndex = rawFileName == null ? void 0 : rawFileName.indexOf(".");
        const cursorPosition = editor.getCursor();
        if (rawFileName === void 0) {
          return;
        }
        const toc = contentToTOC(rawFileName == null ? void 0 : rawFileName.slice(0, periodIndex), editor.getValue(), this);
        editor.replaceRange(toc, cursorPosition);
      }
    });
    this.addCommand({
      id: "Update-toc",
      name: "Update table of contents",
      callback: async () => {
        const file = this.app.workspace.getActiveFile();
        if (!file) {
          return;
        }
        const checkTOC = await checkToc(file);
        if (!checkTOC) {
          return;
        }
        const [updateToc, toc] = await shouldUpdateToc(file, this);
        this.app.vault.process(file, (fileContent) => {
          return updateFileToc(fileContent, toc);
        });
        return;
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-open", async () => {
        this.settings.hiddenLineIndicator = -1;
        await this.saveSettings();
      })
    );
    this.registerEvent(
      this.app.workspace.on("editor-change", async (editor, info) => {
        const file = this.app.workspace.getActiveFile();
        if (!file) {
          return;
        }
        const currentLineIndex = editor.getCursor().line;
        const currentLine = editor.getLine(currentLineIndex);
        const headingChanged = headingUpdated(currentLine);
        const previousLineHadHeading = this.settings.hiddenLineIndicator != -1;
        if (!headingChanged) {
          if (!previousLineHadHeading) {
            return;
          }
          this.settings.hiddenLineIndicator = -1;
          await this.saveSettings();
        }
        this.settings.hiddenLineIndicator = currentLineIndex;
        await this.saveSettings();
        const checkTOC = await checkToc(file);
        if (!checkTOC) {
          return;
        }
        const [updateToc, toc] = await shouldUpdateToc(file, this);
        if (!updateToc) {
          return;
        }
        this.app.vault.process(file, (fileContent) => {
          return updateFileToc(fileContent, toc);
        });
        return;
      })
    );
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};


/* nosourcemap */